# Generated by Django 3.2.13 on 2022-06-16 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='approval_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='lead_org_unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='paas_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=201)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.IntegerField()),
                ('project_title', models.CharField(max_length=201)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_expenditure', models.IntegerField()),
                ('total_contribution', models.IntegerField()),
                ('pag_value', models.IntegerField()),
                ('total_psc', models.IntegerField(default=0)),
                ('approval_status', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.approval_status')),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.country')),
                ('donor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.donor')),
                ('fund', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.fund')),
                ('lead_org_unit', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.lead_org_unit')),
                ('paas_code', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.paas_code')),
                ('theme', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.theme')),
            ],
        ),
    ]
