# Generated by Django 3.2.12 on 2022-02-04 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='total_psc',
        ),
        migrations.AddField(
            model_name='project',
            name='total_psc',
            field=models.IntegerField(default=0),
        ),
    ]
